[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/album/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html?admin=1"
  status = 200
